### PR TITLE
adding new topics from avisd/SG-23204

### PR DESCRIPTION
**Pull request by shaynacohen**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/fa8b02fe480f3d53c9d27eb8a38fc59717fba7c2/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/cbe09d7f85cd4b16908f8673414f9f3e69e1dffd/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/f4cd76a0a2e28e580aebc63c1cd64a24b5201acd/index.html)

**Comment by shaynacohen** [comment]
@eshokrgozar and @000paradox000 , for context, these are topics taken directly from the most viewed community posts with error messages that have been solved. You can preview these here: http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/f4cd76a0a2e28e580aebc63c1cd64a24b5201acd/7ef5be1d/?title=Troubleshooting+Guide > error message guidance

**Review by drewavisautodesk — APPROVED** [review]

**Pull request merged**
