### PR TITLE
SG-32715 Update image

### PR DESCRIPTION
**Pull request by julien-lang**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/09d78353e432ff907c66edb7e11db79b141d543f/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/be03e774b4300c7f4993d4571382338dec1ca7bd/index.html)

**Review by carlos-villavicencio-adsk — APPROVED** [review]
:octocat: :shipit:

**Review by shaynacohen — APPROVED** [review]
LGTM 🎉

**Pull request merged**
