### PR TITLE
SG-21557 community integration page added

### PR DESCRIPTION
**Pull request by zamu5**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/f7ad86ed9f33fc9ebfb66d900dd3ca556aa34b10/index.html)

**Review by thebeeland — CHANGES_REQUESTED** [review]
For this one, let's use a table to organize all of the integrations. Attached here is an image of what you can end up with (though with a row in the table for each of the integrations instead of just the first one like I have here). Also, let's download the images and store them in the repo and reference them directly rather than relying on the external links.

```
| Integration | Engine | Information |
|:-----------:|:------:| ----------- |
| <img src="https://raw.githubusercontent.com/robblau/tk-katana/master/icon_64.png" alt="tk-katana" width="65"/> | tk-katana | Project URL: [https://github.com/robblau/tk-katana](https://github.com/robblau/tk-katana)<br>Project Contributor:  [Lightchaser Animation](https://github.com/LightChaserAnimationStudio)<br>Project Maintainer:<br>Project Description: A {% include product %} Engine for Foundry's Katana |
```

Screen Shot 2021-03-15 at 5 10 41 PM

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/b9541018da3146a85d53039e401cc0a54f7f77a5/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/23379149a01bd770b4d124eac64dd3ef5c1a2b72/index.html)

**Review by thebeeland — APPROVED** [review]
Perfect! I'll merge it now.

**Pull request merged**
