### PR TITLE
Isolation Feature Set setup update

### PR DESCRIPTION
**Pull request by david-richer-adsk**
* Update Isolation features setup to use the new self-serve workflow

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/1fd725e7bf66b4b4d3077213596e996269215fc1/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/6b2f0e3d4ec2097ec84a3f7b1cb9cb8d00bdd854/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/d6087c7c8d6eb264a7da044099669971becc09ac/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/19c578366db8fd9609c119be8ffad9ac9f398cd5/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/46e904b62516509b774c968335107732608e3082/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/fd83a20cc35b0e2f64f1113be2686b42ef688e51/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/079526ad63526ce9db51442e9f96e6c96fd6b4fb/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/87692096327b20015db77d1fffd90f9bf261ef28/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/af34bcfcf0b98eac8919e00bde0ed35691950a3b/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/8fc3a09774b47fff3533a34d6f5db0abc6bb2356/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/57f8bdf95d8927c96e070267329e5c655db9234d/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/07b1b1c6017cab370f4d3e1b7e652f2fd8bcad02/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/07b1b1c6017cab370f4d3e1b7e652f2fd8bcad02/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/e061fd84171889f10c2e26415f233151b5a6be06/index.html)

**Review by comeaug — APPROVED** [review]
nicely done! The s3 config really simplifies things for customers

**Pull request merged**
