### PR TITLE
Correct S3 VPC endpoint verification steps

### PR DESCRIPTION
**Pull request by rlyne**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/a8f0f986c69493077acf28cdc8b1716750599b2a/index.html)

**Review by willis102 — APPROVED** [review]
👍 LGTM

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/fb82a49f5bee5dd265656b76c0d66f661f9a2e64/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/cc31ff5a8dad69f0c98c5fd7542516c4e6709dd1/index.html)

**Pull request merged**
