### PR TITLE
SG-26488_sg About

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/047d484ccc77376c1a4aea7308ef9e1cf1ee36b8/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
find some Shotgun:
image

and
image

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/dcb0a269f9417f19f2f3e1d08fb1063190272369/index.html)

**Review by mathurf — APPROVED** [review]
LGTM!

**Pull request merged**
