### PR TITLE
SG-26524_SG Api Overview

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/d9ab22aadc6ff494316f0996ad25aa58937fe551/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
This URL also needs to be updated:
http://developer.shotgridsoftware.com/python-api/authentication.html

See in ticket https://jira.autodesk.com/browse/SG-26524

**Review by mathurf — APPROVED** [review]
Ian Savoie discussed with Franco and it turns out that the changes for http://developer.shotgridsoftware.com/python-api/authentication.html isneeded in a different repo, so it is part of another PR: https://github.com/shotgunsoftware/python-api/pull/267 .

**Review by NorberMV — APPROVED** [review]
LGTM!

**Pull request merged**
