### PR TITLE
SG-26499_sg ShotGrid Folders

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/0d237bbfa687993c8390bdf21c140b3c533c708e/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
Please update SG icon
image

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/b20486f7c1658a641757a09cf0e5c525ae4485c3/index.html)

**Review by mathurf — APPROVED** [review]
LGTM!

**Pull request merged**
