### PR TITLE
Added first 5 MD files from toolkit-apps, also replaced shotgun instances

### PR DESCRIPTION
**Pull request by zamu5**
Addes the first 5 md files:
tk-flame-export.md
tk-flame-review.md
tk-hiero-export.md
tk-hiero-openinshotgun.md
tk-houdini-alembicnode.md

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/708cd93294d40d2b18e2e1bba8e4f3781f3639dc/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/fec9fc9c4fbcb256bc3e0f59889090b8e9adfca2/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/10d8772116beef9b8e1d65d8bef6495a9e2da73b/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/c9b5aa1082b4443118021f6e59d7a69dccc94fee/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/3f3d7178e0aaad77736de812897165ac8ec8b0c8/index.html)

**Review by thebeeland — APPROVED** [review]

**Pull request merged**
