### PR TITLE
SG-26492_sg Python Console v2

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/22e46a5e65c0ad939e4f8cdcb0420c0583a3a25c/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
As I mentioned in Jira ticket there are 5 images to update, you only did one.
Please do the other 4 images as well

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/4533db89e9d13628f29fdf9c875740c6a0b641c4/index.html)

**Review by mathurf — APPROVED** [review]
LGTM!

**Pull request merged**
