### PR TITLE
SG-26515_sg Photoshop

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/345875071957938bdac2cc847f368bfd1963217b/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
This is the right image to use for the ShotGrid Adobe Panel:
image

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/acf6bd6543fa296d0d925c948b3ccba3be650f1d/index.html)

**Review by mathurf — APPROVED** [review]
LGTM!

**Pull request merged**
