### PR TITLE
Trusted solutions

### PR DESCRIPTION
**Pull request by guillaume-brossard-adsk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/ad12fc27fd52b025209a356cf86da31a1eec2587/index.html)

**Comment by david-richer-adsk** [comment]
All the links at the Shotgun Isolation page are broken: http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/ad12fc27fd52b025209a356cf86da31a1eec2587/f378a164/?title=Shotgun+Isolation

**Comment by guillaume-brossard-adsk** [comment]
@tannazie I am changing the structure a bit, can you have a quick look?

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/44d4fc035c0530f57c38218a60ce130700a7f573/index.html)

**Review by rlyne — APPROVED** [review]

**Pull request merged**
