### PR TITLE
SG-26494_sg Workfiles

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/2f317178debfa8cd3ed5100cd52ade28082c3c7d/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
Found one Shotgun here:
image

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/f396e3b3f55b5835fa025a8c3f8f9219a8310f0f/index.html)

**Review by mathurf — APPROVED** [review]
LGTM

**Pull request merged**
