### PR TITLE
SG-26518_sg_vred

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/67d96b12a07a9dd4e891eb6ad08c296332bd1a5c/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/ff2cc5738401566d063d42ee45de9439f1920024/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
Please change File Open to File Save here:
image

Found 1 Shotgun here
image

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/524cdbea87b3090a93d8ff1f58e0a1e563fe0773/index.html)

**Pull request merged**
