### PR TITLE
Document Media Traffic Isolation using S3 PrivateLink

### PR DESCRIPTION
**Pull request by david-richer-adsk**
* **Media Traffic Isolation** page has been rename **Media Traffic Isolation - S3 Proxy**.
* **Media Traffic Isolation**  page now use the S3 Private Link.

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/fe4e370bbf3941f603fa38bc302eb46f0dd27792/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/568d43419f960d2efeb37b5efd6887d7097da58d/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/ae24facf453b9afdf03820f352e6caccefe81af1/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/604ab33f0eaa52b3aaba843cd02fa2b2aed61e94/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/4b97de296ac0fa45ce81b6d98a6f817c94c699c9/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/38ae22bdf8f6d986b3f237d58ae2275b3a38b945/index.html)

**Comment by rlyne** [comment]
We should also update the high level feature description to reflect this change: https://developer.shotgunsoftware.com/58919eae/

**Review by rlyne — APPROVED** [review]

**Pull request merged**
