### PR TITLE
Update isolation VPCs and NAT Gateways

### PR DESCRIPTION
**Pull request by murph7andrew**
Add new ShotGrid & Transcoder VPC and NAT Gateways to Isolation documentation

vpc-09441e47c87a28dd4 SHOTTS1-prd
	- 54.145.164.228   
	- 3.224.231.216
	- 100.26.115.40
vpc-098e0ff163debc966 SHOTGUN-prd
	- 34.195.16.11
	- 3.234.125.244
	- 3.234.133.244

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/1637f4acd7a397c454f4262ebe0e22959e43c49b/index.html)

**Review by comeaug — COMMENTED** [review]
Can you add what the ips and vpcs map to in the PR request?

**Comment by comeaug** [comment]
doesn't shotts have 2 VPC now? @geffrak

**Comment by geffrak** [comment]
> doesn't shotts have 2 VPC now? @geffrak 

No, only a really big one. The two stack experiment failed.

**Review by geffrak — APPROVED** [review]

**Review by shaynacohen — APPROVED** [review]
Looks good from CXD!

**Pull request merged**
