### PR TITLE
Create michelles-sandbox

### PR DESCRIPTION
**Pull request by GartnerInsights**
This is the sandbox in my playground

### CODE REVIEW

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/425e8cc2535b723d79301ee7237d09aedf051743/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/d8fe2eada1d0ffdd6682583f543f9fee020d5518/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/dc7ee42585270b5d14e7339f7b333e54c114f602/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/c6b12664c9e073ed30140a9e025fab4a263b6365/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/8bde5b95d0fecca10229efc41b7a8a571f88dbce/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/b59c00283297e3f56110a9178065f818d90d06a5/index.html)

**Comment by tannazie** [comment]
this is old and out of date; closing it.

**Pull request closed without merging**
