### PR TITLE
SG-26437_sg Integrations User Guide

### PR DESCRIPTION
**Pull request by francoperroneautodesk**
Changed old "Shotgun" identity to new "ShotGrid" branding.

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/0155b9fb1f18855c36ddd47069f12e9f89a263b7/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
I don't think this is the right image:
docs/en/reference/pipeline-integrations/user-guide/images/sa-integrations-user-guide-download-desktop-02.png

it should be the one with the Download links like this one:
docs/en/reference/pipeline-integrations/user-guide/images/sa-integrations-user-guide-download-desktop-02-v2.png

**Review by mathurf — CHANGES_REQUESTED** [review]
is it possible to update RV icon here?
image

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/89f03da219b6915a2e316c50f329634b32210117/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/afad5f9985053c76bcc9e179d52baef3e85e4798/index.html)

**Review by mathurf — APPROVED** [review]
LGTM!
Nice job looks great!

**Review by 000paradox000 — APPROVED** [review]

**Pull request merged**
