### PR TITLE
SG-26444_sg An Overview of Toolkit

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Review by mathurf — CHANGES_REQUESTED** [review]
Found Shotgun here:
docs/en/guides/pipeline-integrations/administration/images/toolkit-overview/login.png

image

Can you also change the url from .shotgunstudio.com to .shotgrid.autodesk.com

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/a2f0cf889725a1c61330e21c6c40e302e06dcf07/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/bc3ed8ae9c2caa9a2faa748eb691489669f5d81e/index.html)

**Review by mathurf — APPROVED** [review]
LGTM!

**Pull request merged**
