### PR TITLE
SG-26506_sg After Effects

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/f5fb8e08b69437d0684ff65f9ece719aac79c9d8/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
Found some Shotgun and ShotGun ;)
image

image

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/bfedf71fe99c2579e092fcac37d6416fabfffb5d/index.html)

**Review by mathurf — APPROVED** [review]
LGTM!

**Pull request merged**
