### PR TITLE
SG-26438_sg Getting started with configurations

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Review by mathurf — CHANGES_REQUESTED** [review]
Found some Shotgun
image

and this one should be deleted. See with Ariel to do that
image

**Comment by francoperroneautodesk** [comment]
@
> and this one should be deleted. See with Ariel to do that image
@000paradox000

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/0983d7a884662943007dc40631459c8737dbcef9/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/e83fa2458515f2190295f32e8d0db98be24aeb6f/index.html)

**Review by mathurf — APPROVED** [review]
LGTM

**Pull request merged**
