### PR TITLE
Create Dynamic_filesystems

### PR DESCRIPTION
**Pull request by GartnerInsights**
Creating new file for dynamic filesystems and file naming

### CODE REVIEW

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/89a72cfd7671d599ba3f6df48e31b1b139447409/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/710d4204854700cd306e3dbd24b5006155568355/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/0c3ccaaae1867cd585d56c2b3f8eeee14f5115dd/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/a7a3c11b18c3c88646410ee2ad4f78fb39175f5b/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/b2048fc8b422904762ce1d6bf818db9e0cad4b0d/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/0eb2e1a0621d990a99b17c0b373f23728eddee16/index.html)

**Comment by tannazie** [comment]
closing. old and out of date.

**Pull request closed without merging**
