### PR TITLE
SG-21170-ROUND3 [ZD to AKN] Update links referenced from code to the old support site to point to AKN

### PR DESCRIPTION
**Pull request by 000paradox000**
Adjust support url

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/d2a9fbf9c3df59898a7e6b2187079142473e1d02/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/7a3cfdc335c83abdd7c4649a460e3a9eb140c998/index.html)

**Review by shaynacohen — APPROVED** [review]
Thank you for fixing all of these! 🙏

**Review by mathurf — APPROVED** [review]
LGTM!
:shipit:

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/bcca8325b3ee93e7a56edcf781fe56301910c4b0/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/7dba208cb888160376037e31232b5ed50ac4e5fd/index.html)

**Review by mathurf — APPROVED** [review]
LGTM
:shipit:

**Pull request merged**
