### PR TITLE
translation update 20220328

### PR DESCRIPTION
**Pull request by sunhang36**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/0132baae43e16cfec9dcdc49203983e32610ff5a/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/3538247ccefc1af9eb34c14ad98e96c19e1a0073/index.html)

**Comment by sunhang36** [comment]
Hi @shaynacohen ,could you please help review and merge this translation update? Thanks!

**Review by shaynacohen — COMMENTED** [review]
It looks like the old logo was replaced with the new one. Can that be fixed before we merge?

**Comment by sunhang36** [comment]
Hi @shaynacohen , thanks for pointing this out. I have fixed them.

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/b1e4bd531b7447c22b21e96f5db719fb8970c83b/index.html)

**Review by shaynacohen — APPROVED** [review]

**Pull request merged**
