### PR TITLE
SG-28090 fix to broken ps api link

### PR DESCRIPTION
**Pull request by shaynacohen**

### CODE REVIEW

**Comment by shaynacohen** [comment]
Fixing by removing the broken link. LMK if you are aware of any other link this should be.

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/fcd7c3d30aec8905f8d31701bcb8d9f7e494189b/index.html)

**Comment by shaynacohen** [comment]
Here is the preview: http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/fcd7c3d30aec8905f8d31701bcb8d9f7e494189b/8d461cbe/?title=Photoshop

**Review by NorberMV — APPROVED** [review]
LGTM!

**Pull request merged**
