### PR TITLE
Translation update i18n-2

### PR DESCRIPTION
**Pull request by sunhang36**

### CODE REVIEW

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/28f865f621bd60ef3c304796c8db2ad151eeb491/index.html)

**Comment by sunhang36** [comment]
```
Liquid Exception: Invalid syntax for include tag: title="ヒント" content="Desktop を開いているときに新しいプロジェクトを作成した場合、新しいプロジェクトを表示するには、**プロジェクト** ウィンドウを更新しなければならないことがあります。デスクトップの右下にあるプロファイルの**アバター**を選択して、[Refresh Projects]を選択します。 Valid syntax: {% include file.ext param='value' param2='value' %} in ja/toolkit/learning-resources/guides/advanced_config.md
```
Error when generting jpn doc. Now we can't open the jpn doc.

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/ef55fc4784b97d0c8523082c32038de8c48252b0/index.html)

**Comment by manneohrstrom** [comment]
Passing this over to @tannazie to review and merge!

**Pull request merged**
