### PR TITLE
updates to troubleshooting guide

### PR DESCRIPTION
**Pull request by shaynacohen**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/778a4d075014757f4aeb28bd8faff45b372e848f/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/51a4fea33807f0c2878ca36c0e7e05a4efdb59c6/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/4b48c3b694f7daf265fbabca7c9cb8e844e645aa/index.html)

**Comment by shaynacohen** [comment]
@drewavisautodesk before I go any further, I'd like to squash and merge this request. I was having issues relocating the files, but have successfully been able to update the TOC. Approve if this looks good, thanks!

**Review by drewavisautodesk — APPROVED** [review]

**Pull request merged**
