### PR TITLE
SG-26510_sg Flame

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/b02599e49a862bffc5790ffc52330d1511c39568/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/bb59e7fbb7b84b24f8dd29b27bfdffdc8d98017d/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/b24d4324bbfd70e10e2abada8a693845b7f5c545/index.html)

**Review by mathurf — APPROVED** [review]
LGTM

**Pull request merged**
