### PR TITLE
SG-26441_sg Filesystem configuration

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Review by mathurf — CHANGES_REQUESTED** [review]
Sorry we didn't tell you but all yml file names haven't changed
so it is still shotgun.yml

You can revert 3 images with that yml file

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/83ca32ce93f187952141ea1dbc042a3b9f8f4dbd/index.html)

**Review by mathurf — APPROVED** [review]
LGTM!

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/49a98951538922ae1656b5a54813adbb915d00ff/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/c6c52e2e97e91abf909dfa68fdf426084ba3f58b/index.html)

**Review by 000paradox000 — APPROVED** [review]

**Pull request closed without merging**
