### PR TITLE
SG-26504_sg 3dsMax

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/13ce9ceb8793956afaae35529450623c89262d15/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
Found some Shotgun
image

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/d6a73f2406cc15b550d3903a4969fff3bebf1301/index.html)

**Review by mathurf — APPROVED** [review]
LGTM!

**Pull request merged**
