### PR TITLE
SG-26442_sg Animation Pipeline Tutorial

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/5b4583aa8b579ad2986b3653d01cd96b16fcf5a1/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
Found some Shotgun ;)
image

This is not the right image at bottom of the SG Desktop app.
image

It should be this text: ShotGrid Desktop
image

image

This image can be deleted, it doesn't exists anymore. But to avoid error in the browser it means that documentation will need to be updated as well to not try to load it. Wee with Ariel for that.
image

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/a78aa9a5f924fb1b2f020e362f4d1354d9d540f4/index.html)

**Comment by francoperroneautodesk** [comment]
Still need to check the deleted image with Ariel!

**Review by mathurf — CHANGES_REQUESTED** [review]
This image still has Shotgun in it
docs/en/guides/pipeline-integrations/workflows/images/tutorial/image_62.png

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/0b99b869178bd8c92bccf0651447542ab785978d/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
Found another Shotgun:
image

Also do not forget that we need to remove this image since it doesn't exists anymore.
image

See with @000paradox000 to also remove it in documentation.

**Comment by francoperroneautodesk** [comment]
> Found another Shotgun: image
> 
> Also do not forget that we need to remove this image since it doesn't exists anymore. image
> 
> See with @000paradox000 to also remove it in documentation.

Ariel will remove that image in a new ticket

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/11da77e4d7eca36a8484a7e92549aea83c0eae26/index.html)

**Review by mathurf — APPROVED** [review]
LGTM!

**Pull request merged**
