### PR TITLE
SG-25384 sg Developer Site Rebranding Logos

### PR DESCRIPTION
**Pull request by NorberMV**
This pr replaces the following logos with the new sg logos :

From docs/images/landing_page:
- sg.png  
- sg_large_logo.png

From docs/ja/images/landing_page :
- sg.png             
- sg_large_logo.png  

From docs/ko/images/landing_page :
- sg.png				
- sg_large_logo.png

From docs/site-metadata :
- android-chrome-192x192.png
- android-chrome-384x384.png
- apple-touch-icon.png
- favicon.ico
- favicon-16x16.png
- favicon-32x32.png
- mstile-150x150.png	

From docs/zh_CN/images/landing_page :
- sg.png				
- sg_large_logo.png	

From docs/en/reference/pipeline-integrations/images/engines :

- 3ds_max_icon_256.png  
- alias_icon_256.png	
- create_icon_256.png	
- desktop_icon_256.png	
- flame_icon_256.png	
- maya_icon_256.png		
- shell_icon_256.png
- shotgrid_icon_256.png

From docs/images/landing_page/ :
- rv.png
From docs/en/guides/pipeline-integrations/administration/images/Integration-admin-guide/ :
- icon_256.png	# Done

From docs/ja/guides/pipeline-integrations/administration/images/Integration-admin-guide/ :
- icon_256.png	
From docs/ko/guides/pipeline-integrations/administration/images/Integration-admin-guide/ :
- icon_256.png
From docs/zh_CN/guides/pipeline-integrations/administration/images/Integration-admin-guide/ :
- icon_256.png

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/87272e4f95b6e138aceb844a94b436d275345344/index.html)

**Review by mathurf — COMMENTED** [review]
these icons should only have S icon (no SG under it)
docs/site-metadata/favicon-16x16.png

**Review by mathurf — CHANGES_REQUESTED** [review]
also please updates all images under https://github.com/shotgunsoftware/developer.shotgunsoftware.com/tree/SG-25384_SG_Developer_Site_Rebranding_Logos/docs/en/reference/pipeline-integrations/images/

Specifically the Autodesk Engines icons

**Review by mathurf — COMMENTED** [review]
Also please replace all rv.png with the new RV icon

**Review by mathurf — COMMENTED** [review]
there is also this icon for all languages like :
https://github.com/shotgunsoftware/developer.shotgunsoftware.com/blob/SG-25384_SG_Developer_Site_Rebranding_Logos/docs/ja/guides/pipeline-integrations/administration/images/Integration-admin-guide/icon_256.png

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/714a68c716a1fdabfeba02bb6ef90f0bdd0030f6/index.html)

**Comment by mathurf** [comment]
> Please also find for all dropper.png icon like this one: https://github.com/shotgunsoftware/developer.shotgunsoftware.com/blob/SG-25384_SG_Developer_Site_Rebranding_Logos/docs/ja/guides/pipeline-integrations/administration/images/community-shared-integrations/dropper.png
> 
> you can replace it with this one: https://github.com/shotgunsoftware/tk-rv-shotgunreview/blob/SG-25870_tk-rv-shotgunreview_Rebranding/icon_256.png

This is a community shared integration... So not sure what we should do 🤔

**Comment by NorberMV** [comment]
> > Please also find for all dropper.png icon like this one: https://github.com/shotgunsoftware/developer.shotgunsoftware.com/blob/SG-25384_SG_Developer_Site_Rebranding_Logos/docs/ja/guides/pipeline-integrations/administration/images/community-shared-integrations/dropper.png
> > you can replace it with this one: https://github.com/shotgunsoftware/tk-rv-shotgunreview/blob/SG-25870_tk-rv-shotgunreview_Rebranding/icon_256.png
> 
> This is a community shared integration... So not sure what we should do 🤔

I push the requested changes,  only waiting for an answer in the #squad-sg-rebranding to be sure about this modification in the community shared integration logos.

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/d173f7e38667755f4e5e65d928289085f5623384/index.html)

**Review by mathurf — COMMENTED** [review]
This is about SG Create
https://github.com/shotgunsoftware/developer.shotgunsoftware.com/blob/SG-25384_SG_Developer_Site_Rebranding_Logos/docs/en/reference/pipeline-integrations/images/engines/create_icon_256.png

We Should use SG Create new icon:
https://share.autodesk.com/sites/DevAssetResourceCenter/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=t8LU7T&cid=7499879d%2D3561%2D4e17%2Db3b0%2D7965d567097d&FolderCTID=0x01200059477CCABA7B1B4188740AB8C45E3F39&id=%2Fsites%2FDevAssetResourceCenter%2FShared%20Documents%2FFY23%20Final%20Dev%20Assets%2FShotGrid%5FCreate%5F2023%5FMac%2FL16%5FCRE%5Flaunch%2FL16%5FCRE%5Flaunch%2D256x256%2Epng&parent=%2Fsites%2FDevAssetResourceCenter%2FShared%20Documents%2FFY23%20Final%20Dev%20Assets%2FShotGrid%5FCreate%5F2023%5FMac%2FL16%5FCRE%5Flaunch

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/f568a7cf335926c69e37740effc94313244d0703/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/c4ca350372536d201d711d0bded64ed5e1f0e110/index.html)

**Review by mathurf — APPROVED** [review]
LGTM!

Please DO NOT merge yet

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/5a0de04c808bda3898f7d2bd72c330cfa340d343/index.html)

**Pull request merged**
