### PR TITLE
First version of S3 replication documentation

### PR DESCRIPTION
**Pull request by david-richer-adsk**
First version of S3 replication documentation

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/13a56145c51526d577178f348048635261e5488f/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/80a9ca2bfbbd854576d61eb263110188776a0b0e/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/9aebcc6d70d3bdb2af48d83695161b12c79e926b/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/ecb35efcbe5721315d1701c0b0efda9470b6a355/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/cfd416521149d5ba9cbd25869591fc4a5307d02c/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/1645f74e2202ef947e34219b1dc78317af78b6e3/index.html)

**Comment by david-richer-adsk** [comment]
Thanks for the fix!

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/dc1cc0e947eaad7901b99bdd0e3c3da3e322e64b/index.html)

**Pull request merged**
