### PR TITLE
SG-26445_sg Adding an app

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Review by 000paradox000 — APPROVED** [review]

**Review by mathurf — CHANGES_REQUESTED** [review]
Found Shotgun here ;)
docs/en/guides/pipeline-integrations/getting-started/images/installing_app/13_app_in_maya.png

image

**Review by mathurf — CHANGES_REQUESTED** [review]
Found Shotgun here ;)
docs/en/guides/pipeline-integrations/getting-started/images/installing_app/3_list_of_apps.png
image

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/4e2b06b0f4d0eb889c690fb2e725d5b7e5ef8cdc/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/228c18c22e0337ab346dfb99b7d6752725f4823b/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
You should revert your changes done for the overview page.
Commit 9195daa2e61ac525d6abb55a944d46ecebf28a1d

**Pull request closed without merging**
