### PR TITLE
SG-30739-duguids-webhook-improvements

### PR DESCRIPTION
**Pull request by shaynacohen**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/8d6fc11c7550bd9179ece5e43c6e76e2736b0ea4/index.html)

**Comment by shaynacohen** [comment]
Here is the preview: http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/8d6fc11c7550bd9179ece5e43c6e76e2736b0ea4/3d448f5e/?title=Webhooks

**Review by slewery — APPROVED** [review]
Looks great!

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/dc1bb1da1cf5bb063939152af4a533ad6a050624/index.html)

**Pull request merged**
