### PR TITLE
SG-26478_sg Beyond Your First Project

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/64568b64ade983e523da713690846d7fabcb0535/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
These icons shouldn't have been changed
image

**Review by mathurf — APPROVED** [review]
LGTM!

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/3a601a8dcef8daab5829361e00fba5e555e54c7e/index.html)

**Pull request merged**
