### PR TITLE
SG-26513_sg Motion Builder

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/2ef6a13a5851c9d8af92d0923dc3f3c603531d3c/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
Wow those images are so old!
Can you replace them this these ones?
First image:
image

and at least replace publish app in the second image with this one if possible. Maybe just make sure you are still using the project name Demo project from other apps
image

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/da1932bb37875876dd341b46b78e559bef067523/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
You replaced the wrong app. You should have replaced the Publish app:
image

And can you please make sure previous project name is kept?
Replace that header with one having Demo project:
image

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/afe7ce00049c3645361d90fe2de3e3c2fef8f211/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
Found some Shotgun:
image

**Review by mathurf — APPROVED** [review]
LGTM!

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/9e2d971d8d0162feb4464c2ddfe121bf00d612a2/index.html)

**Pull request merged**
