### PR TITLE
SG-26505_sg 3dsMax Plus v2

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/43da655ed7e6a9ebb32e4adba7e7b2c41baacfb4/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
You forgot to fix this Shotgun
image

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/619a74124a6fb914ee6df87a59f914afc9ba0495/index.html)

**Review by mathurf — APPROVED** [review]
LGTM!

**Pull request merged**
