### PR TITLE
fix 404 for contribution doc in loc language

### PR DESCRIPTION
**Pull request by sunhang36**
Eg: https://developer.shotgunsoftware.com/ja/contribution/contribution/ind_contrib_agmt_for_shotgun_developer_documentation.pdf

### CODE REVIEW

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/a904bc7180934853afa63a9f006f69e4e7f4b855/index.html)

**Comment by sunhang36** [comment]
Hi @manneohrstrom @robblau this PR is trying to fix a minor bug about 404 when clicking the contribution pdf. But as you can check from the preview website, the UI is not working correctly. May I know if I missed something?

**Comment by tannazie** [comment]
Hello! The weird styling in the preview is a known issue; not sure @manneohrstrom is actively working on it at the moment, but it's on his radar and in his queue.

**Comment by robblau** [comment]
This looks fine to me, although it would be nice to not have to replicate the pdf for all languages since there is no intent to translate it. @manneohrstrom is there a way to do that?

**Comment by manneohrstrom** [comment]
Hi @sunhang36 ! I will look at fixing the preview functionality shortly - it broke as we moved the doc site into its final location. @robblau agree makes no sense to duplicate - the system we use for i18n ([polyglot](https://polyglot.untra.io/)) already does exactly this for normal markdown pages but looks like it's not happening for non-markdown pages like pdfs. I'll look into if we can configure it to do this!

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/0eb7cf758f37d7956491612de93d10cc2fcce654/index.html)

**Comment by manneohrstrom** [comment]
previews are now back - let me check on the contribution pfds!

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/e7d5ec7cd075820e13bf9eee0c2aabdc82992b15/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/1ecdfdd90307242fefaa170dd5961afd2e740a6d/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/48d54c0f6d6a5ee9e7ad7e36335188c3793d19d9/index.html)

**Comment by manneohrstrom** [comment]
@sunhang36 Can you check out my latest changes to see that you are happy with them? The solution i ended up with was surprisingly simple - i just moved the contribution agreement pdfs into an `all_langs` area - where we can store all content (pdfs, zips, other stuff) that is generic across languages. Does that seem like a good approach to you? 

If yes, then this is ✅ready to be merged!

**Pull request merged**
