### PR TITLE
Create comparison_chart_sandbox

### PR DESCRIPTION
**Pull request by GartnerInsights**
This is for testing and playing with the configruation comparison chart

### CODE REVIEW

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/36191c366fea30bb15b260cb1ff2520c56e8ddf6/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/bafc629ca16e9b8bb373f15339ef52d65a4e23cb/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/2fefaff24afc8180704dff60d20f6df455c02a5b/index.html)

**Comment by tannazie** [comment]
closing this pull request as we've made fixes in the getting_started_branch itself, and tha branch has been released.

**Pull request closed without merging**
