### PR TITLE
Editing-App-Setting-round2

### PR DESCRIPTION
**Pull request by GartnerInsights**

### CODE REVIEW

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/27af534e119e16ffd0938e2e95310200b2074b99/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/d54e0b0e5bbdd79682099e28ddd82bd01b0bdd29/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/f53dcc0e893d1de5fd8b41b0985be1c5dbbc1286/index.html)

**Comment by GartnerInsights** [comment]
I updated the numbering, changed a reference from Toolkit to Maya integration, fixed a couple of text formats and fixed some grammar...

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/ec867010076745712d70b5f6844c2d1f8c935a20/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/adf8645b6d2d28fe25c8e5fc855aa09375257a2d/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/22ce531f16347b5d8ffc4b6c1a732a090fa13ae8/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/e80de37882cc5b9e48704efe0970193a8396161b/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/577a2aba9aaa92d6b3b194a99ed299527a86cb86/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/8f90178b46d802058b684406e6457df5f699fde7/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/85fb72a681774340df524eb44751df2d5b34a06c/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/6fd9f7ef5677666db8ca0485e3120607098597bf/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/b14d730b5ecd4b18cf8f4550f73e3ae1eccafb71/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/b42b8455761f62280e98bc3aa4cdfd7e3d85725d/index.html)

**Comment by tannazie** [comment]
old and out of date

**Pull request closed without merging**
