### PR TITLE
Update advanced_config.md

### PR DESCRIPTION
**Pull request by GartnerInsights**
Updating formatting and using standards from Pipeline Tutorial as a guide

### CODE REVIEW

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/f22ecf84f73e63629772908c4bd19d0c1ad43a39/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/433d846d00eb4cda6e2d7275f708107e42cda2b3/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/6664edd7060e2619e6ebdec0ec34bcfb967d4855/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/779d5e3803f42661f288c41a98cf95d5361ff8ba/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/44d1e5b0fe373fe43df4933e594f8afaabb6078b/index.html)

**Comment by tannazie** [comment]
closing this one; old and out of date

**Pull request closed without merging**
