### PR TITLE
Improving AMI docs and replacing thinglink images

### PR DESCRIPTION
**Pull request by shaynacohen**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/c8e2fa3b57b3816fadf2a14f39fcb4ac3f5c0c7f/index.html)

**Comment by mathurf** [comment]
Hi @shaynacohen 

This seems more for ShotGrid web team.

**Comment by shaynacohen** [comment]
Thanks @mathurf .... I think it's OK for me to publish. I'm just fixing some things.

**Review by mathurf — APPROVED** [review]

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/0e2c31a9029df955b66e7957e4d4e9c654c2ab85/index.html)

**Comment by shaynacohen** [comment]
Need to take another pass at fixing the numbering and bullets blerg

**Pull request merged**
