### PR TITLE
SG-26491_sb Shotgun Publisher API

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/10664fcc4d53bef0b2b6f5aec2e566c39ba46b5d/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/fde15023e991f5c93136f43a44db1506e0db961e/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
Found some Shotgun
image

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/2a6be2db68366113f840913ed05e4fce23090f4e/index.html)

**Review by mathurf — APPROVED** [review]
LGTM!

**Review by mathurf — CHANGES_REQUESTED** [review]
There are other pages that needs to be updated. See in Jira ticket https://jira.autodesk.com/browse/SG-26491

**Pull request closed without merging**
