### PR TITLE
SG-26514_sg Nuke

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/0d29ed39f7b51bcc2df99278ae2c763798fd8344/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
ShotGrid his darker here:
image

**Review by mathurf — CHANGES_REQUESTED** [review]
It seems one image haven't been changed (Last one at the end of the page)
image

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/e9f4d7dd4ec0acbdb386c8834c7e2c34dd93989d/index.html)

**Review by mathurf — APPROVED** [review]
LGTM!

**Pull request merged**
