### PR TITLE
SG-27879 Make Developer Shotgrid Site Compliant With Our Privacy

### PR DESCRIPTION
**Pull request by NorberMV**
This PR updates the tk-doc-generator latest commit in master which implements the Tealium Script as part of the Tealium instrumentation tagging plan for the developer.shotgridsoftware.com site.

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/d6b26f10dad30439b9739985f93dc955bcb513a3/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/5554512fbde3ed4ec14d948a161c640799e10f03/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/0c7cbfba8d4d4ca4b96a3dbf8eb323f65fa87a88/index.html)

**Review by 000paradox000 — APPROVED** [review]
LGTM

**Pull request merged**
