### PR TITLE
SG-26492_sg Python Console

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/f00d8d97ef02d71091c76b77286b8e9084c187e7/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
Couple of places where Shotgun shouldn't have been changed to ShotGrid.
See in this example:
image

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/de08176e7819c2edcba349cdc981de40cd85060d/index.html)

**Review by mathurf — APPROVED** [review]
LGTM

**Pull request merged**
