### PR TITLE
Getting started round two

### PR DESCRIPTION
**Pull request by GartnerInsights**

### CODE REVIEW

**Comment by GartnerInsights** [comment]
Fixed formatting, some small grammar fixes and changed a reference from Toolkit to Maya integration.

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/fb6ec79a2f6d13ab8601ecf98b618202a2d5e317/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/a36018cb1b7c1a105f4e81a515cdf83558a803d6/index.html)

**Comment by tannazie** [comment]
this is old. closing it.

**Pull request closed without merging**
