### PR TITLE
First addition of breakdown2 link to toc.yml

### PR DESCRIPTION
**Pull request by rob-aitchison**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/7f2dbe5d6d03006a6767fc9bf515265184bdf6ca/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/8cae531509d98cec9825b4f786755097cbd5a0f7/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/8c371a7ad1ecf560ee82735ba63f79972b05c97e/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/8c3cc3684fd1b673bc73325372314b648b2f9473/index.html)

**Review by barbara-darkshot — COMMENTED** [review]
hey @rob-aitchison, maybe we could split the Breakdown2 doc in two entries? one for the API under the "Toolkit APIs" menu entry and another one for the app itself under the "Apps" menu? like it's already done for the publish app/api

**Comment by rob-aitchison** [comment]
> hey @rob-aitchison, maybe we could split the Breakdown2 doc in two entries? one for the API under the "Toolkit APIs" menu entry and another one for the app itself under the "Apps" menu? like it's already done for the publish app/api

Hey @barbara-darkshot , that is a great suggestion and does apply to multiple apps now. We should definitely link to it in both but we may want to enhance the usage part of the documentation before doing so. What do you think? Thanks again!

**Comment by barbara-darkshot** [comment]
👍 agreed!
I think we should also improve the api documentation by adding more examples of how we can use it

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/5aef5f6a5d5f0d4ebed9461b72de48f88570bdfc/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/0a0fca606afafea235a92f27fe5692f0f472db63/index.html)

**Review by NorberMV — APPROVED** [review]
LGTM !

**Comment by rob-aitchison** [comment]
Created a new ticket - SHOT-4115 - for the work flagged in the conversation above.

**Pull request merged**
