### PR TITLE
SG-29849 python support updates v2

### PR DESCRIPTION
**Pull request by shaynacohen**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/364e582e87da90fe9f7fc41dbea40f6df2a8f608/index.html)

**Review by julien-lang — APPROVED** [review]
LGTM!

**Comment by shaynacohen** [comment]
Thanks @julien-lang ! Making a couple more formatting adjustments after previewing, then I'll publish.

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/536d88b415170aedc2ded4ed6c368c1a877d986a/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/0d7435ac3bda058604a0b271a0c37594d6080fe8/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/67ced717364146bcf86b73ff4e668835bcada004/index.html)

**Pull request merged**
