### PR TITLE
SG-26502_sg Flame Export

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/6317bd30c2171883b68276443dcc16662a2a2a4a/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
This screenshot has changed
https://github.com/shotgunsoftware/developer.shotgunsoftware.com/pull/339/files#diff-388593161416d93f0a113f710eb55b5d78149fdffc8a2f084d95d5483667a620

see here:
https://github.com/shotgunsoftware/tk-flame-export/commit/81791c56df1ecc188f25532c2c16f6a301468dd3#diff-f3fa5eeacf8fe3f908aae4f48ee4d897f893e60a7792c5759039c692936ba828

Basically now it is only Flame icon --> ShotGrid icon

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/34d1c94f69622f7ca48967fa671d43df72dccb25/index.html)

**Review by mathurf — APPROVED** [review]
LGTM!

**Pull request merged**
