### PR TITLE
SG-26439_sg Editing a Config

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/c03f9b6ae6e51be40781e7ac401e4382fd6cb417/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
Found 2 Shotgun ;)

image

image

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/fa3d48a436244c05fae2e2f1c48a150f89f4fa75/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/87269f0ec1610b02e8e81f45903112b76a1eac25/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
Sorry I missed than one... SHOTGRID needs be be updated to ShotGrid
image

**Review by 000paradox000 — APPROVED** [review]

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/ea3e72765ee5d93233be52812c822fbb702d3878/index.html)

**Review by mathurf — APPROVED** [review]
LGTM!

**Pull request merged**
