### PR TITLE
SG-30398 new landing page edits

### PR DESCRIPTION
**Pull request by shaynacohen**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/874b2387871c8a60dfa6877dee26fb74de3eb8c5/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/f5035661117e5c181db1b2ebd2f4c046f2f538e2/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/f045a3c4e01c4ceecde00820cb289541f64723bc/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/4389ba5de77c681cb6f25bbc83da5ed6d39b759e/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/ad98d1a9bf3271451a52d988017e91d69d2ca8c7/index.html)

**Comment by shaynacohen** [comment]
@julien-lang @carlos-villavicencio-adsk , are you OK with me publishing this update to the landing page ASAP?
Screenshot 2023-10-30 at 5 31 05 PM

**Review by julien-lang — APPROVED** [review]
LGTM!

**Pull request merged**
