### PR TITLE
SG-26496_sg Hiero/Nuke Studio Open in ShotGrid v2

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/4cb4ba6926019441702428fcd38254dde50feba3/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
You forgot 1 Shotgun
image

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/f4e4b9af1f14e7369909afbc4da59f3de693bc4d/index.html)

**Review by mathurf — APPROVED** [review]
LGTM!

**Pull request merged**
