### PR TITLE
SG-26495_sg Hiero/Nuke Studio Export

### PR DESCRIPTION
**Pull request by francoperroneautodesk**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/d5d4e360543fc26fe4981fe7fb29fcd5bef5b0f2/index.html)

**Review by mathurf — CHANGES_REQUESTED** [review]
Found some Shotgun:
image

image

image

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/b16af1f6fef6cc8802a9b82e79a6897bb29d1361/index.html)

**Review by mathurf — APPROVED** [review]
LGTM!

**Pull request merged**
