### PR TITLE
SG-29931 updating desktop version added to docs

### PR DESCRIPTION
**Pull request by shaynacohen**

### CODE REVIEW

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/7e126c2851d38a2a23b1ed482682a718e7d51e6f/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/e0d270de8b0a709de88f75f8cb23d883f9fa9ece/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/ce8429994be0f61ca71705ea1d5dc32c17cf8d09/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/e89979bb4b6a3fdfc7238b45b8e1162a5f439101/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/3ab9508cb7c4428d8e0ae465f22ae281503e3d0f/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/37e8ef48c1ed5267f2523d182adb6a012f58eef8/index.html)

**Comment by toolkitty** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/2f956240f1eff259d9885270213e99e6e8d87696/index.html)

**Review by julien-lang — APPROVED** [review]
LGTM

**Pull request merged**
